# Hayden Owens
# 1/21/2022
# Operating Systems - Project 1
# Project 1 Makefile

all:	filecopy	treecopy

filecopy:	filecopy.c
	gcc -g -std=c99 -Wall -o filecopy filecopy.c

treecopy:	treecopy.c
	gcc -g -std=c99 -Wall -o treecopy treecopy.c

clean:
	rm -f filecopy
	rm -f treecopy
